# Generated by Django 2.1 on 2018-10-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181021_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_status',
            field=models.IntegerField(),
        ),
    ]
