# Generated by Django 2.1 on 2018-10-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181021_0727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttributes',
            new_name='ProductAttribute',
        ),
    ]
