# Generated by Django 2.1 on 2018-11-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181021_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='products/static/uploads/banner-03.jpg', max_length=200, upload_to='products/static/uploads'),
            preserve_default=False,
        ),
    ]
